### PR TITLE
Fix DCCs bel placement for top and bottom mux

### PR DESCRIPTION
**Pull request by mtdudek**
Split top and bottom DCCs to correct tiles.
Signed-off-by: Maciej Dudek <mdudek@antmicro.com>

### CODE REVIEW

**Comment by gatecat** [comment]
Have you checked the wires are correct for this? istr the Lattice tools puts them logically all in the first tile and just splits the bitstream bits, a problem better solved inside `get_bel_tiles` instead of moving the Bel location.

**Comment by mtdudek** [comment]
You are right, it will be better to keep them in first tile. I'll change that and update PR

**Comment by mtdudek** [comment]
@gatecat  Fixed

**Comment by gatecat** [comment]
Looks perfect, thanks!

**Pull request merged**
