### PR TITLE
Add PLL fuzzer for LIFCL-17

### PR DESCRIPTION
**Pull request by mtdudek**
This PR is amid at adding PLL support to LIFCL-17

Signed-off-by: Maciej Dudek <mdudek@antmicro.com>

### CODE REVIEW

**Comment by gatecat** [comment]
All LGTM to me so far, have you tried running it?

**Comment by mtdudek** [comment]
Yes I tried. Unfortunately after switching to Radiant later then 2.0 122 fuzzer does not work. It can't find bits responsible for enabling PLL even in LIFCL-40.

**Comment by mtdudek** [comment]
So I recently run design with PLL through Radiant. It turns out that database is out of date.
Turning on PLL does not enable bits in bitstream, also bits configuring PLL are out of date and are incorrect.
I would suggest running PLL fuzzers once again and update DB.

**Comment by mtdudek** [comment]
@gatecat  Could you take a look?

**Comment by gatecat** [comment]
Can you explain a bit more why the watched bits thing is needed?

**Comment by mtdudek** [comment]
There is an issue with 121 fuzzer, V2I_KVCO_SEL was setting bits that were already used by LDT_LOCK_SEL.
This made bitstream faulty.
Adding watched_bits, fuzzer only looks at given range/bits and check if they change.
It's somewhat similar to bit_mask, but with spin on it. It only looks for bits with exact(frame, bit) pair.
It solved issue I had with PLL.

**Comment by mtdudek** [comment]
@gatecat I hope this explains what watched_bits are.

**Comment by gatecat** [comment]
Ideally instead of the `watched_bits` which seems to create a future chicken-and-egg problem perhaps you could find a more targeted way of stopping the bits from changing when you modify V2I_KVCO_SEL ?

**Comment by mtdudek** [comment]
So I've changed 121 PLLIP fuzzer to no longer use `watched_bits`. Should I remove rust infrastructure as well? @gatecat

**Comment by gatecat** [comment]
Yeah, sounds good, if its not needed then I'd rather it was removed on the rust side too.

**Comment by mtdudek** [comment]
Removed rust infrastructure @gatecat 
Also if you could look at #23

**Comment by mtdudek** [comment]
@gatecat, could you take a look at this PR? I've increased range of V2I from (10,90) to (10,120) based on the fact that some bit configurations were missing and I was curious, if increasing range would find them.

**Comment by gatecat** [comment]
LGTM, sorry for the delay at dealing with this

**Pull request merged**
